In [ ]:
## Unzipping Files
import zipfile
with zipfile.ZipFile('../data/raw/Archive.zip', 'r') as zip_ref:
    zip_ref.extractall('../data/raw/')

In [2]:
import pandas as pd

In [3]:
pd.options.display.float_format = '{:,.2f}'.format

In [6]:
df_orders.shape

(3421083, 7)

In [7]:
print(f"""Number of rows: {df_orders.shape[0]}
      Number of columns: {df_orders.shape[1]}
      on {df_orders.shape[0]}""")

Number of rows: 3421083
      Number of columns: 7
      on 3421083

In [5]:
df_orders = pd.read_csv('../data/raw/orders.csv')
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [8]:
# Reading Data from CSV file
df_orders.head(10)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00
5,3367565,1,prior,6,2,7,19.00
6,550135,1,prior,7,1,9,20.00
7,3108588,1,prior,8,1,14,14.00
8,2295261,1,prior,9,1,16,0.00
9,2550362,1,prior,10,4,8,30.00

In [9]:
df_orders.tail(10)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421073,2307371,206209,prior,5,4,15,3.00
3421074,3186442,206209,prior,6,0,16,3.00
3421075,550836,206209,prior,7,2,13,9.00
3421076,2129269,206209,prior,8,3,17,22.00
3421077,2558525,206209,prior,9,4,15,22.00
3421078,2266710,206209,prior,10,5,18,29.00
3421079,1854736,206209,prior,11,4,10,30.00
3421080,626363,206209,prior,12,1,12,18.00
3421081,2977660,206209,prior,13,1,12,7.00
3421082,272231,206209,train,14,6,14,30.00

In [10]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [11]:
df_orders.rename(columns={'order_id': 'Order ID', 'customer_id': 'User ID', 'order_dow': 'Day of Week'}, inplace=True)

In [12]:
df_orders.head(10)

,Order ID,user_id,eval_set,order_number,Day of Week,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00
5,3367565,1,prior,6,2,7,19.00
6,550135,1,prior,7,1,9,20.00
7,3108588,1,prior,8,1,14,14.00
8,2295261,1,prior,9,1,16,0.00
9,2550362,1,prior,10,4,8,30.00

In [13]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Order ID                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   Day of Week             int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [14]:
df_orders.drop(columns=['eval_set'], inplace=True)

In [15]:
df_orders.head()

,Order ID,user_id,order_number,Day of Week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.00
2,473747,1,3,3,12,21.00
3,2254736,1,4,4,7,29.00
4,431534,1,5,4,15,28.00

In [16]:
df_orders.describe()

,Order ID,user_id,order_number,Day of Week,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [17]:
df_orders[[ 'order_hour_of_day', 'days_since_prior_order']].describe()

       order_hour_of_day  days_since_prior_order
count       3,421,083.00            3,214,874.00
mean               13.45                   11.11
std                 4.23                    9.21
min                 0.00                    0.00
25%                10.00                    4.00
50%                13.00                    7.00
75%                16.00                   15.00
max                23.00                   30.00

In [18]:
df_orders.describe(exclude='integer')

       days_since_prior_order
count            3,214,874.00
mean                    11.11
std                      9.21
min                      0.00
25%                      4.00
50%                      7.00
75%                     15.00
max                     30.00

In [19]:
df_orders.head()

,Order ID,user_id,order_number,Day of Week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.00
2,473747,1,3,3,12,21.00
3,2254736,1,4,4,7,29.00
4,431534,1,5,4,15,28.00

In [20]:
df_orders[[ 'days_since_prior_order']].describe()

       days_since_prior_order
count            3,214,874.00
mean                    11.11
std                      9.21
min                      0.00
25%                      4.00
50%                      7.00
75%                     15.00
max                     30.00

In [21]:
df_IQR = df_orders['days_since_prior_order'].quantile(0.75) - df_orders['days_since_prior_order'].quantile(0.25)
df_IQR

np.float64(11.0)

In [22]:
df_orders['days_since_prior_order'].quantile(0.75)

np.float64(15.0)

In [23]:
df_orders_mid50 = df_orders[(df_orders['days_since_prior_order'] >= 4) & (df_orders['days_since_prior_order'] <= 15)]
df_orders_mid50.shape
df_orders_mid50.describe()
df_orders_mid50.head()

,Order ID,user_id,order_number,Day of Week,order_hour_of_day,days_since_prior_order
1,2398795,1,2,3,7,15.00
7,3108588,1,8,1,14,14.00
10,1187899,1,11,4,8,14.00
12,1501582,2,2,5,10,10.00
14,738281,2,4,2,10,8.00

In [24]:
df_orders_mid50.user_id.value_counts()

user_id
175724    70
49973     63
112654    63
103507    62
134329    62
          ..
206173     1
206179     1
206184     1
206185     1
206198     1
Name: count, Length: 183772, dtype: int64

In [25]:
df_orders_mid50.info()

<class 'pandas.DataFrame'>
Index: 1799050 entries, 1 to 3421081
Data columns (total 6 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Order ID                int64
 1   user_id                 int64
 2   order_number            int64
 3   Day of Week             int64
 4   order_hour_of_day       int64
 5   days_since_prior_order  float64
dtypes: float64(1), int64(5)
memory usage: 96.1 MB

In [26]:
df_orders_mid50.index.all()

np.True_

In [27]:
len(df_orders_mid50.index.unique())

1799050

In [28]:
len(df_orders_mid50)

1799050

In [35]:
df_orders_mid50[['mean_days_since_prior_order', 'max_days_since_prior_order']] = [11.11, 30]

In [48]:
df_orders_mid50.head(10)

,Order ID,user_id,order_number,Day of Week,order_hour_of_day,days_since_prior_order
1,2398795,1,2,3,7,15.00
7,3108588,1,8,1,14,14.00
10,1187899,1,11,4,8,14.00
12,1501582,2,2,5,10,10.00
14,738281,2,4,2,10,8.00
15,1673511,2,5,3,11,8.00
16,1199898,2,6,2,9,13.00
17,3194192,2,7,2,12,14.00
19,1718559,2,9,2,9,8.00
20,1447487,2,10,1,11,6.00

In [47]:
df_orders_mid50.drop('max_days_since_prior_order', inplace=True, axis=1)