## Imports

In [3]:
import pandas as pd
from utils import age_group_label
from utils import income_band

## Create dummy data

In [4]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

## Functions usage

In [5]:
df_customers_dummy["age_gro up"] = df_customers_dummy["age"].apply( age_group_label)
df_customers_dummy["income_band"] = df_customers_dummy["income"].apply(income_band,low=20000, high=80000)

df_customers_dummy

  customer  age  income   age_gro up income_band
0        A   22   18000        Minor         Low
1        B   35   42000  Middle-aged      Medium
2        C   47   72000  Middle-aged      Medium
3        D   63   95000       Senior        High
4        E   29   25000        Minor      Medium